const keys = [
  { key: "`", keyRu: "ё", code: "Backquote" },
  { key: "1", code: "Digit1" },
  { key: "2", code: "Digit2" },
  { key: "3", code: "Digit3" },
  { key: "4", code: "Digit4" },
  { key: "5", code: "Digit5" },
  { key: "6", code: "Digit6" },
  { key: "7", code: "Digit7" },
  { key: "8", code: "Digit8" },
  { key: "9", code: "Digit9" },
  { key: "0", code: "Digit0" },
  { key: "-", code: "Minus" },
  { key: "=", code: "Equal" },
  { key: "BACKSPACE", code: "Backspace" },
  { key: "TAB", code: "Tab" },
  { key: "q", keyRu: "й", code: "KeyQ" },
  { key: "w", keyRu: "ц", code: "KeyW" },
  { key: "e", keyRu: "у", code: "KeyE" },
  { key: "r", keyRu: "к", code: "KeyR" },
  { key: "t", keyRu: "е", code: "KeyT" },
  { key: "y", keyRu: "н", code: "KeyY" },
  { key: "u", keyRu: "г", code: "KeyU" },
  { key: "i", keyRu: "ш", code: "KeyI" },
  { key: "o", keyRu: "щ", code: "KeyO" },
  { key: "p", keyRu: "з", code: "KeyP" },
  { key: "[", keyRu: "х", code: "BracketLeft" },
  { key: "]", keyRu: "ъ", code: "BracketRight" },
  { key: "\\", code: "Backslash" },
  { key: "DEL", code: "Delete" },
  { key: "CAPSLOCK", code: "CapsLock" },
  { key: "a", keyRu: "ф", code: "KeyA" },
  { key: "s", keyRu: "ы", code: "KeyS" },
  { key: "d", keyRu: "в", code: "KeyD" },
  { key: "f", keyRu: "а", code: "KeyF" },
  { key: "g", keyRu: "п", code: "KeyG" },
  { key: "h", keyRu: "р", code: "KeyH" },
  { key: "j", keyRu: "о", code: "KeyJ" },
  { key: "k", keyRu: "л", code: "KeyK" },
  { key: "l", keyRu: "д", code: "KeyL" },
  { key: ";", keyRu: "ж", code: "Semicolon" },
  { key: "'", keyRu: "э", code: "Quote" },
  { key: "ENTER", code: "Enter" },
  { key: "SHIFT", code: "ShiftLeft" },
  { key: "z", keyRu: "я", code: "KeyZ" },
  { key: "x", keyRu: "ч", code: "KeyX" },
  { key: "c", keyRu: "с", code: "KeyC" },
  { key: "v", keyRu: "м", code: "KeyV" },
  { key: "b", keyRu: "и", code: "KeyB" },
  { key: "n", keyRu: "т", code: "KeyN" },
  { key: "m", keyRu: "ь", code: "KeyM" },
  { key: ",", keyRu: "б", code: "Comma" },
  { key: ".", keyRu: "ю", code: "Period" },
  { key: "/", keyRu: ".", code: "Slash" },
  { key: "ArrowUp", code: "ArrowUp" },
  { key: "SHIFT", code: "ShiftRight" },
  { key: "CTRL", code: "ControlLeft" },
  { key: "W", code: "MetaLeft" },
  { key: "ALT", code: "AltLeft" },
  { key: " ", code: "Space" },
  { key: "ALT", code: "AltRight" },
  { key: "ArrowLeft", code: "ArrowLeft" },
  { key: "ArrowDown", code: "ArrowDown" },
  { key: "ArrowRight", code: "ArrowRight" },
  { key: "CTRL", code: "ControlRight" },
];

export default keys;
